name: Build and deploy application

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: 'environment to run on'
        required: true
        default: 'development'
        
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

permissions:
      id-token: write
      contents: read

jobs:
  build:
    name: Build LogicApp Demo
    runs-on: self-hosted
    environment: ${{ github.event.inputs.environment }}
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4
    - name: Package
      run: (cd src/LogicAppsStandardDemo; mkdir -p ../../output; zip -r ../../output/workflow.zip .)
    - name: 'Upload Package'
      uses: actions/upload-artifact@v4
      with:
        name: workflow
        path: ./output/
        retention-days: 1

  Deploy:
      runs-on: self-hosted
      needs: build
      environment: ${{ github.event.inputs.environment }}
      steps:
      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
          # client-id: ${{ secrets.AZURE_CLIENT_ID }}
          # tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          # subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
            az group show --name "rg-rg-s12p"

      - name: 'get deployment package'
        uses: actions/download-artifact@master
        with:
          name: workflow
          path: ./output/

      - run: |
          echo "Azure Region: ${{vars.AZURE_REGION}}"
          echo "LogicApp Name: ${{vars.LOGICAPP_NAME}} "
          echo "Workload Environment: ${{vars.WORKLOAD_ENVIRONMENT}}"

      - name: 'Deploy LogicApp with Functions Action'
        uses: Azure/functions-action@v1
        id: la
        with:
          app-name: ${{ vars.LOGICAPP_NAME }}
          package: ./output/workflow.zip
          
      - name: 'update logicapp settings'
        uses: azure/appservice-settings@v1
        with:
          app-name: ${{ vars.LOGICAPP_NAME }}
          app-settings-json: '[{"name":"CallRestApiURI","value":"${{vars.CallRestApiURI}}","slotSetting":"false"},{"name":"APIBaseURI","value":"https://webhook.site/c57923f4-f729-49ec-b123-aab28ec21ad3","slotSetting":"false"}]'
          connection-strings-json: '[{"name":"testconnstr","value":"testconnstrvalue", "type":"Custom", "slotSetting":"false"}]'
          #Note: can also use general-settings-json to manage workflow and general settings



