name: Build and deploy application

on:
  push:
    branches:
      - main
  workflow_dispatch:   # optional manual trigger
    inputs:
      environment:
        description: "Environment to deploy"
        required: false
        type: choice
        options:
          - dev
          - qa

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build LogicApp Demo
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Package
        run: |
          cd src/LogicAppsStandardDemo
          mkdir -p ../../output
          zip -r ../../output/workflow.zip .

      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: workflow
          path: ./output/
          retention-days: 1

  Deploy-Dev:
    runs-on: self-hosted
    needs: build
    environment: dev

    steps:
      - name: Az CLI login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Download package
        uses: actions/download-artifact@v4
        with:
          name: workflow
          path: ./output/

      - name: Deploy LogicApp (Dev)
        run: |
          az webapp deployment source config-zip \
            --resource-group ${{ vars.RESOURCE_GROUP_NAME }} \
            --name ${{ vars.LOGICAPP_NAME }} \
            --src ./output/workflow.zip

      - name: Update LogicApp Settings
        uses: azure/appservice-settings@v1
        with:
          app-name: ${{ vars.LOGICAPP_NAME }}
          app-settings-json: |
            [
              {"name":"CallRestApiURI","value":"${{ vars.CallRestApiURI }}","slotSetting":"false"},
              {"name":"APIBaseURI","value":"https://webhook.site/...","slotSetting":"false"}
            ]

  Deploy-QA:
    runs-on: self-hosted
    needs: Deploy-Dev   # 👈 ensures it runs AFTER dev
    environment: qa     # 👈 THIS triggers approval gate

    steps:
      - name: Download package
        uses: actions/download-artifact@v4
        with:
          name: workflow
          path: ./output/

      - name: Az CLI login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy LogicApp (QA)
        run: |
          az webapp deployment source config-zip \
            --resource-group ${{ vars.QA_RESOURCE_GROUP }} \
            --name ${{ vars.QA_LOGICAPP_NAME }} \
            --src ./output/workflow.zip

      - name: Update LogicApp Settings
        uses: azure/appservice-settings@v1
        with:
          app-name: ${{ vars.QA_LOGICAPP_NAME }}
          app-settings-json: |
            [
              {"name":"CallRestApiURI","value":"${{ vars.QA_CallRestApiURI }}","slotSetting":"false"},
              {"name":"APIBaseURI","value":"https://webhook.site/...","slotSetting":"false"}
            ]
